import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "~/lib/utils";
import Header from "~/components/headers/header";
import Footer from "~/components/footer";
import FixedFooter from "~/components/fixed-footer";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-figtree" });

export const metadata: Metadata = {
  title: "Airbnb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          figtree.variable,
        )}
      >
        <Header />
        {children}
        <div className="pt-10">
          <Footer />
        </div>
        <FixedFooter />
      </body>
    </html>
  );
}
